name: REAL REACT CI/CD

on:
  push:
    branches: ['main']
    tags:
      - 'prod-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # 버전 형식을 수정합니다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm manually
        run: npm install -g pnpm@8.x

      - name: Cache node modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Setup .env
        run: |
          echo "VITE_API_URL=${{ secrets.REAL_VITE_API_URL }}" >> .env.local

      - name: Build
        run: |
          pnpm run build
          pwd
          ls -al

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.REAL_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REAL_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REAL_AWS_DEFAULT_REGION }}
        run: |
          aws s3 sync ./dist s3://${{ secrets.REAL_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.REAL_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REAL_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REAL_AWS_DEFAULT_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.REAL_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
